# Generated by Django 2.2 on 2020-12-31 16:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ecu_id', models.CharField(max_length=20)),
                ('generation', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('start_at', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
                ('cc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='')),
                ('offset', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_vn', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=200)),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('recommend', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(max_length=200)),
                ('readable', models.BooleanField(default=True)),
                ('writable', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('start_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BikeParameterExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.IntegerField()),
                ('parameter_id', models.IntegerField()),
                ('expression', models.CharField(default='', max_length=200)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('bike_id', 'parameter_id')},
            },
        ),
        migrations.CreateModel(
            name='BikeParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('bike_id', models.IntegerField()),
                ('parameter_id', models.IntegerField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('bike_id', 'row', 'column')},
            },
        ),
    ]
