# Generated by Django 2.2 on 2020-12-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeparameter',
            name='is_used',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
