# Generated by Django 2.2 on 2020-12-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='readable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='writable',
            field=models.BooleanField(default=True),
        ),
    ]
