# Generated by Django 2.2 on 2020-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_vn', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=200)),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('recommend', models.FloatField()),
            ],
        ),
    ]
