# Generated by Django 2.2 on 2020-12-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0002_bikeparameter_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeparameterexpression',
            name='is_used',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
