# Generated by Django 2.2 on 2020-12-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0003_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.IntegerField()),
                ('parameter_id', models.IntegerField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('expression', models.CharField(max_length=200)),
            ],
        ),
    ]
