# Generated by Django 2.2 on 2020-12-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0005_auto_20201230_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bikeparameter',
            unique_together={('bike_id', 'parameter_id')},
        ),
    ]
